apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
  namespace: docker-training
  labels:
    app: app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-backend
  template:
    metadata:
      labels:
        app: app-backend
    spec:
      containers:
        - name: app-backend
          image: mateuszgti/dockerowy-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app-backend
  namespace: docker-training
spec:
  selector:
    app: app-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
