apiVersion: v1
kind: Service
metadata:
  name: app-backend
  namespace: argocd
spec:
  selector:
    app: app-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
